#!/usr/bin/env python3
"""Regenerate the C catalogue from the reviewed, immutable .NET v2 snapshot."""
import argparse, json, pathlib
root = pathlib.Path(__file__).resolve().parents[1]
p = argparse.ArgumentParser()
p.add_argument('--check', action='store_true')
p.add_argument('--source', type=pathlib.Path, default=root/'tests/fixtures/ble-metric-encodings-v2.json')
a = p.parse_args()
entries = json.loads(a.source.read_text())
lines = ['/* Generated by tools/update-ble-metrics.py; v2 encodings are immutable. */', 'static const nm_ble_metric_encoding encodings[] = {']
for e in entries:
    strings = ', '.join(json.dumps(e[k], ensure_ascii=True) for k in ('Format', 'Metric', 'Unit'))
    numbers = ', '.join(format(e[k], '.17g') for k in ('Scale', 'Offset', 'Minimum', 'Maximum'))
    lines.append('    {' + strings + ', ' + numbers + '},')
lines.append('};')
output = '\n'.join(lines) + '\n'
target = root/'firmware/main/ble_metric_catalogue.inc'
if a.check:
    if target.read_text() != output:
        raise SystemExit('BLE catalogue differs; run tools/update-ble-metrics.py')
else:
    target.write_text(output)
